src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Salary__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Salary</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Team_Board__c</fullName>
        <label>Team Board</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Who&apos;s on First</fullName>
                </value>
                <value>
                    <fullName>Pantera</fullName>
                </value>
                <value>
                    <fullName>Sophomore Risers</fullName>
                </value>
                <value>
                    <fullName>Bronto Bolts</fullName>
                </value>
                <value>
                    <fullName>Elegantly Wasted</fullName>
                </value>
                <value>
                    <fullName>Free Agent</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>4th and Drunk</fullName>
                </value>
                <value>
                    <fullName>Freedom Buck o Five</fullName>
                </value>
                <value>
                    <fullName>Yager Bombers</fullName>
                </value>
                <value>
                    <fullName>UsCis.gov</fullName>
                </value>
                <value>
                    <fullName>Silly Nannies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Players</relationshipLabel>
        <relationshipName>Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player_Team_Relationship__c.object
<CustomObject>
    <description>junction object to track player to teams and historical salary paid</description>
    <fields>
        <fullName>Games_Played__c</fullName>
        <label>Games Played</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipName>Salaries_over_time</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>Salaries_over_time</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player-Team-Relationship</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Player-Team-Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player-Team-Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <formula>If(MONTH(TODAY()) &gt;7, TEXT(YEAR(TODAY())+ 1),TEXT(YEAR(TODAY())))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WWUtils.cls
public class WWUtils {
    
    // use this method pre draft to update all players to new salary.
    public static void updateToNextYearSalary(){      
        List<Player__c> players = [SELECT id, 
                                   Team_Board__c,
                                   Salary__c,
                                   Name
                                   FROM player__c
                                   Where Salary__c != 0
                                   And Team_Board__c != 'Free Agent'];
        system.debug(players);
        for(Player__c p:players){
            p.Salary__c = p.Salary__c + 3;
        } 
        update players;
    }
    
    // use this method pre draft to update free agents to 0 salary.
    public static void updateFreeAgentsToZero(){
        List<Player__c> players = [SELECT id, 
                                   Team_Board__c,
                                   Salary__c,
                                   Name
                                   FROM player__c
                                   Where Salary__c != 0
                                   And Team_Board__c = 'Free Agent'];
        system.debug(players);
        for(Player__c p:players){
            p.Salary__c = 0;
        } 
        update players;
    }
    
    // create player team user rels. one time load.
    public static void createPTRbulk(){
        List<Player__c> players = [SELECT id, 
                                   Team_Board__c,
                                   Team__c,
                                   Salary__c,
                                   Name
                                   FROM player__c];
        
        List<Player_Team_Relationship__c> ptrs = new List<Player_Team_Relationship__c >();
        
        for(player__c p:players){
            Player_Team_Relationship__c ptr = new Player_Team_Relationship__c();
            ptr.player__c = p.Id;
            ptr.team__c = p.Team__c;
            ptr.season__c = '2017';
            ptr.Salary__c = p.Salary__c;
			ptr.Games_Played__c = 16;
            ptrs.add(ptr);
        }
        insert ptrs;
    }
    
}